server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    fetch-registry: true #eureka 서버로부터 인스턴스의 정보를 주기적으로 가져옴
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
